name: anhnct
channels:
  - pytorch
  - nvidia
  - anaconda
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _tflow_select=2.3.0=mkl
  - abseil-cpp=20211102.0=h27087fc_1
  - absl-py=1.3.0=pyhd8ed1ab_0
  - aiosignal=1.2.0=pyhd8ed1ab_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - astunparse=1.6.3=pyhd8ed1ab_0
  - async-timeout=4.0.2=py38h06a4308_0
  - attrs=22.1.0=pyh71513ae_1
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.07.19=h06a4308_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.2.0=pyhd8ed1ab_0
  - certifi=2022.6.15=py38h06a4308_0
  - cffi=1.15.0=py38hd667e15_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.3=unix_pyhd8ed1ab_2
  - cryptography=37.0.1=py38h9ce1e76_0
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - debugpy=1.5.1=py38h295c915_0
  - entrypoints=0.4=py38h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - ffmpeg=4.3=hf484d3e_0
  - flatbuffers=2.0.0=h2531618_0
  - freetype=2.11.0=h70c0345_0
  - frozenlist=1.2.0=py38h7f8727e_0
  - giflib=5.2.1=h7b6447c_0
  - gmp=6.2.1=h2531618_2
  - gmpy2=2.1.2=py38heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - google-pasta=0.2.0=pyh8c360ce_0
  - grpc-cpp=1.46.1=h33aed49_0
  - h5py=3.6.0=nompi_py38hfbb2109_100
  - hdf5=1.12.1=nompi_h2750804_100
  - icu=58.2=hf484d3e_1000
  - idna=3.3=pyhd3eb1b0_0
  - importlib_resources=5.10.0=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jedi=0.18.1=py38h06a4308_1
  - jpeg=9e=h7f8727e_0
  - jsonschema=4.16.0=pyhd8ed1ab_0
  - jupyter_client=7.2.2=py38h06a4308_0
  - jupyter_core=4.10.0=py38h06a4308_0
  - jupyterlab_widgets=3.0.3=pyhd8ed1ab_0
  - keras=2.9.0=py38h06a4308_0
  - keras-preprocessing=1.1.2=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.19.3=h3790be6_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libblas=3.9.0=12_linux64_mkl
  - libcblas=3.9.0=12_linux64_mkl
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.9.0.20=0
  - libcurand=10.3.5.119=0
  - libcurl=7.84.0=h91b91d3_0
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libedit=3.1.20221030=h5eee18b_0
  - libev=4.33=h516909a_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_0
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libgomp=11.2.0=h1234567_0
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - liblapack=3.9.0=12_linux64_mkl
  - libnghttp2=1.46.0=hce63b2e_0
  - libnpp=11.7.4.75=0
  - libnvjpeg=11.8.0.2=0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.20.1=h4ff587b_0
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.10.0=ha56f1ee_2
  - libstdcxx-ng=11.2.0=h1234567_0
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - lz4-c=1.9.3=h295c915_1
  - markupsafe=2.1.1=py38h0a891b7_1
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - more-itertools=8.12.0=pyhd3eb1b0_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py38h06a4308_0
  - multidict=6.0.2=py38h0a891b7_1
  - nbformat=5.7.0=pyhd8ed1ab_0
  - ncurses=6.3=h7f8727e_2
  - nettle=3.7.3=hbbd107a_1
  - numpy-base=1.23.3=py38h31eccc5_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1q=h7f8727e_0
  - opt_einsum=3.3.0=pyhd8ed1ab_1
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.0.1=py38h22f2fdc_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyasn1=0.4.8=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyjwt=2.6.0=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyrsistent=0.18.1=py38h0a891b7_1
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.13=h12debd9_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=pyhd8ed1ab_0
  - python-flatbuffers=2.0=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytorch-cuda=11.7=h778d358_5
  - pytorch-mutex=1.0=cuda
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyzmq=23.2.0=py38h6a678d5_0
  - re2=2022.04.01=h27087fc_0
  - readline=8.1.2=h7f8727e_1
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.9=hbd366e4_1
  - sqlite=3.39.3=h5082296_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sympy=1.12=py38h06a4308_0
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - tensorflow-estimator=2.9.0=py38h06a4308_0
  - termcolor=2.0.1=pyhd8ed1ab_1
  - tk=8.6.11=h1ccaba5_1
  - tornado=6.1=py38h27cfd23_0
  - typing_extensions=4.9.0=py38h06a4308_1
  - urllib3=1.26.9=py38h06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - widgetsnbextension=4.0.3=pyhd8ed1ab_0
  - wrapt=1.14.1=py38h0a891b7_0
  - xz=5.2.5=h7f8727e_1
  - yaml=0.2.5=h7f98852_2
  - yarl=1.7.2=py38h0a891b7_2
  - zeromq=4.3.4=h2531618_0
  - zlib=1.2.12=h7f8727e_2
  - zstd=1.4.9=haebb681_0
  - pip:
    - accelerate==0.30.1
    - addict==2.4.0
    - aenum==3.1.15
    - aiohttp==3.9.5
    - albumentations==1.1.0
    - aliyun-python-sdk-core==2.15.0
    - aliyun-python-sdk-kms==2.16.2
    - annotated-types==0.6.0
    - antlr4-python3-runtime==4.9.3
    - anyio==3.6.2
    - apex==0.1
    - appdirs==1.4.4
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - argparse==1.4.0
    - astor==0.8.1
    - autograd==1.6.2
    - autograd-gamma==0.5.0
    - autopep8==2.0.0
    - av==11.0.0
    - beautifulsoup4==4.12.3
    - bleach==5.0.1
    - blinker==1.4
    - braceexpand==0.1.7
    - calflops==0.2.9
    - chumpy==0.70
    - cmake==3.29.3
    - colorama==0.4.6
    - coloredlogs==15.0.1
    - crcmod==1.7
    - cvxopt==1.3.0
    - cycler==0.11.0
    - cython==0.29.32
    - dataclasses-json==0.6.7
    - decorator==4.4.2
    - decord==0.6.0
    - defusedxml==0.7.1
    - deprecated==1.2.14
    - dill==0.3.8
    - dirtyjson==1.0.8
    - distro==1.9.0
    - dnspython==2.6.1
    - docker-pycreds==0.4.0
    - ecos==2.0.13
    - efficientnet-pytorch==0.7.1
    - einops==0.7.0
    - email-validator==2.1.1
    - export==0.2.1
    - fairscale==0.4.13
    - fastapi==0.110.0
    - filelock==3.7.0
    - fire==0.6.0
    - fonttools==4.33.3
    - formulaic==1.0.1
    - fsspec==2024.2.0
    - ftfy==6.1.3
    - funcsigs==1.0.2
    - future==1.0.0
    - fvcore==0.1.5.post20221221
    - gast==0.3.3
    - gdown==4.4.0
    - gitdb==4.0.9
    - gitpython==3.1.27
    - google-api-core==2.19.1
    - google-api-python-client==2.138.0
    - google-auth==2.29.0
    - google-auth-httplib2==0.2.0
    - google-auth-oauthlib==1.2.1
    - googleapis-common-protos==1.63.2
    - graphlib-backport==1.1.0
    - greenlet==3.0.3
    - grpcio==1.64.0
    - gunicorn==21.2.0
    - h11==0.14.0
    - hdbscan==0.8.28
    - httpcore==1.0.4
    - httplib2==0.22.0
    - httptools==0.6.1
    - httpx==0.27.0
    - huggingface-hub==0.24.0
    - humanfriendly==10.0
    - imageio==2.34.0
    - imageio-ffmpeg==0.4.9
    - imgaug==0.4.0
    - importlib-metadata==4.12.0
    - interface-meta==1.3.0
    - iopath==0.1.10
    - ipdb==0.13.13
    - ipython==8.12.3
    - ipython-genutils==0.2.0
    - itsdangerous==2.1.2
    - jinja2==3.1.2
    - jmespath==0.10.0
    - joblib==1.4.2
    - json-tricks==3.17.3
    - jupyter-server==1.21.0
    - jupyterlab-pygments==0.2.2
    - kaggle==1.6.6
    - keras-importance-sampling==0.10
    - kiwisolver==1.4.2
    - lazy-loader==0.3
    - lifelines==0.27.8
    - lightning==2.2.2
    - lightning-utilities==0.11.2
    - lit==18.1.6
    - llama-cloud==0.0.9
    - llama-index==0.10.56
    - llama-index-agent-openai==0.2.9
    - llama-index-cli==0.1.12
    - llama-index-core==0.10.56
    - llama-index-embeddings-openai==0.1.11
    - llama-index-indices-managed-llama-cloud==0.2.5
    - llama-index-legacy==0.9.48
    - llama-index-llms-openai==0.1.26
    - llama-index-multi-modal-llms-openai==0.1.8
    - llama-index-program-openai==0.1.6
    - llama-index-question-gen-openai==0.1.3
    - llama-index-readers-file==0.1.30
    - llama-index-readers-llama-parse==0.1.6
    - llama-parse==0.4.9
    - lmdb==1.5.1
    - loguru==0.6.0
    - lxml==5.2.2
    - markdown==3.3.7
    - markdown-it-py==3.0.0
    - marshmallow==3.21.3
    - matplotlib==3.5.2
    - mdurl==0.1.2
    - mistune==2.0.4
    - mmcv==2.1.0
    - mmcv-full==1.7.2
    - mmdeploy==1.3.1
    - mmdeploy-runtime==1.3.1
    - mmdeploy-runtime-gpu==1.3.1
    - mmdet==3.2.0
    - mmengine==0.10.3
    - mmpose==1.3.1
    - model-index==0.1.11
    - moviepy==1.0.3
    - multiprocess==0.70.16
    - munch==2.5.0
    - munkres==1.1.4
    - mypy-extensions==1.0.0
    - nbclassic==0.4.5
    - nbclient==0.7.0
    - nbconvert==7.2.2
    - nest-asyncio==1.6.0
    - networkx==2.8.1
    - nibabel==3.2.2
    - ninja==1.11.1.1
    - nltk==3.8.1
    - notebook==6.5.1
    - notebook-shim==0.2.0
    - numexpr==2.8.6
    - numpy==1.24.4
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-ml-py==12.535.133
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nccl-cu12==2.20.5
    - nvidia-nvjitlink-cu12==12.4.99
    - nvidia-nvtx-cu11==11.7.91
    - nvidia-nvtx-cu12==12.1.105
    - nvitop==1.3.2
    - oauth2client==4.1.3
    - oauthlib==3.2.0
    - objgraph==3.6.1
    - omegaconf==2.3.0
    - onnx==1.15.0
    - onnxconverter-common==1.14.0
    - onnxruntime==1.17.1
    - onnxruntime-gpu==1.16.3
    - openai==1.37.0
    - opencv-contrib-python==4.10.0.84
    - opencv-python==4.10.0.84
    - opencv-python-headless==4.5.5.64
    - opendatalab==0.0.10
    - openmim==0.3.9
    - openxlab==0.0.34
    - ordered-set==4.1.0
    - orjson==3.9.15
    - osqp==0.6.7
    - oss2==2.17.0
    - packaging==23.2
    - paddleocr==2.8.1
    - paddlepaddle==2.6.1
    - pandas==2.0.3
    - pandocfilters==1.5.0
    - pathlib==1.0.1
    - pathtools==0.1.2
    - pip==24.2
    - platformdirs==4.2.0
    - portalocker==2.8.2
    - pretrainedmodels==0.7.4
    - prettytable==3.3.0
    - proglog==0.1.10
    - prometheus-client==0.15.0
    - promise==2.3
    - prompt-toolkit==3.0.47
    - proto-plus==1.24.0
    - protobuf==3.19.4
    - psutil==5.9.1
    - ptflops==0.7.3
    - py-cpuinfo==9.0.0
    - pyarrow==2.0.0
    - pyasn1-modules==0.2.8
    - pyclipper==1.3.0.post5
    - pycocotools==2.0.7
    - pycodestyle==2.9.1
    - pycryptodome==3.20.0
    - pydantic==2.6.4
    - pydantic-core==2.16.3
    - pydantic-extra-types==2.6.0
    - pydantic-settings==2.2.1
    - pydrive==1.3.1
    - pygments==2.17.2
    - pypdf==4.3.1
    - pyre-extensions==0.0.23
    - python-docx==1.1.2
    - python-dotenv==1.0.1
    - python-graphviz==0.20.3
    - python-multipart==0.0.9
    - python-slugify==8.0.4
    - pytorch-lightning==1.1.4
    - pytz==2023.4
    - pywavelets==1.3.0
    - pyyaml==5.4.1
    - qdldl==0.1.7.post2
    - qudida==0.0.4
    - rapidfuzz==3.9.4
    - rarfile==4.2
    - regex==2023.12.25
    - requests==2.28.2
    - rich==13.4.2
    - rsa==4.8
    - safetensors==0.4.2
    - scikit-image==0.21.0
    - scikit-learn==1.3.2
    - scikit-survival==0.22.2
    - scikit-video==1.1.11
    - scipy==1.10.1
    - seaborn==0.13.2
    - send2trash==1.8.0
    - sentry-sdk==1.6.0
    - setproctitle==1.2.3
    - setuptools==60.2.0
    - shapely==2.0.3
    - shortuuid==1.0.9
    - simplejson==3.19.2
    - smmap==5.0.0
    - sniffio==1.3.0
    - soupsieve==2.3.2.post1
    - split-folders==0.5.1
    - sqlalchemy==2.0.31
    - starlette==0.36.3
    - striprtf==0.0.26
    - style==1.1.0
    - tabulate==0.9.0
    - tenacity==8.5.0
    - tensorboard==2.14.0
    - tensorboard-data-server==0.7.2
    - terminado==0.17.0
    - terminaltables==3.1.10
    - text-unidecode==1.3
    - thop==0.1.1-2209072238
    - threadpoolctl==3.1.0
    - tifffile==2023.7.10
    - tiktoken==0.7.0
    - timm==1.0.3
    - tinycss2==1.2.1
    - tokenizers==0.19.1
    - tomli==2.0.1
    - torch==2.0.0+cu117
    - torch-geometric==2.5.3
    - torchaudio==2.0.2
    - torchmetrics==0.10.3
    - torchsummary==1.5.1
    - torchvision==0.15.0+cu117
    - tqdm==4.66.4
    - traitlets==5.5.0
    - transformers==4.42.4
    - triton==2.0.0
    - typing-extensions==4.10.0
    - typing-inspect==0.9.0
    - tzdata==2024.1
    - ujson==5.3.0
    - ultralytics==8.1.34
    - update==0.0.1
    - uritemplate==4.1.1
    - uvicorn==0.28.0
    - uvloop==0.19.0
    - vidaug==0.1
    - wandb==0.17.5
    - warmup-scheduler==0.3
    - watchfiles==0.21.0
    - wcwidth==0.2.13
    - webdataset==0.2.86
    - webencodings==0.5.1
    - websocket-client==1.4.1
    - websockets==12.0
    - werkzeug==2.1.2
    - wget==3.2
    - xformers==0.0.18
    - xtcocotools==1.14.3
    - yacs==0.1.8
    - yapf==0.40.2
    - zipp==3.8.0
prefix: /mnt/disk1/anaconda3/envs/anhnct
